# baseURL
@baseURL = http://localhost:3000

###
# Find All Hotel
GET {{ baseURL }}/hotel

###
# Find Hotel By Id
GET {{ baseURL }}/hotel/65e588927cad7be7702edbd4

###
# Create Hotel
POST {{ baseURL }}/hotel
Content-Type: application/json

{
    "name": "MatHotel",
    "location": "Tours",
    "description": "description",
    "picture_list": "picture_list"
    
}

###
# Modify Hotel By Id
PUT {{ baseURL }}/hotel/1
Content-Type: application/json

{
    "email": "example@email.com",
    "password": "password1"
}

###
# Delete Hotel By Id
DELETE {{ baseURL }}/hotel/1
